version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - 3456:3456
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    environment:
      PORT: 3000
      PROXY_API: http://api:3456/
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
